### ISSUE TITLE
Two space characters in nova names

### ISSUE THREAD

**Issue by l-takeda** [Bill-Gray/galnovae#2]
Thank you for the effort on maintaining this catalog. It is very useful! I only have two suggestions... The GCVS_ID fields for V351 Pup, V868 Cen, V496 Sct and V992 Sco have two space characters between the number and the constellation. It can be inconvenient to someone that is matching the catalog by the objects' names. Also, I missed Z Cam and AT CnC in the list. Thank you.

**Comment by Bill-Gray** [comment]
Thanks for the comments.  The four extra spaces were both no-questions-about-it wrong and quite easy to fix.  Fixing it also caused me to notice and fix two objects with no GCVS designation listed in the file : V1428 Cen from 2012 and HV Cet from 2008.

Adding Z Cam,  AT Cnc,  and other UGZs is another issue.  I currently don't have _any_ of them.  The current GCVS lists 43 of them (including a few "UGZ:" types,  i.e.,  "we _think_ it's that type,  but don't hold us to it.")  List shown below.

I'd be okay with adding these objects.  I am really a bit outside my field here (I'm an asteroid tracking guy).  Seems to me that if there are "missing" types in this catalog (possibly beyond just the UGZs),  a decent start would be to look for stars of those types in GCVS and merge them in.
```
desig         RA (J2000) dec     type   max mag   min mag   band
RX    And *|010435.52 +411757.8 |UGZ   | 10.2    |  15.1    |V
IW    And  |010108.91 +432326.0 |UGZ:  | 13.7    |  17.3    |p
V0510 Aqr  |214653.36 -021820.4 |UGZ:  | 16.79   |  20.25   |CV
V0991 Aql *|193534.85 +063345.7 |UGZ:  | 13.4    |< 15.0    |p
Z     Cam *|082513.18 +730639.1 |UGZ   |  9.8    |  14.5    |V
SY    Cnc *|090103.32 +175356.0 |UGZ   | 10.5    |  14.5    |V
AT    Cnc *|082836.90 +252002.9 |UGZ   | 12.7    |  16.2    |B
WZ    CMa  |071849.18 -270742.8 |UGZ:  | 14.5    |< 17.     |p
V0513 Cas  |001814.90 +661813.8 |UGZ:  | 15.5    |< 17.2    |p
BP    CrA  |183650.89 -372553.4 |UGZ:  | 13.5    |  15.9    |V
SW    Crt  |115225.44 -243102.0 |UGZ:  | 15.2    |  17.5    |p
EM    Cyg *|193840.11 +303028.4 |UGZ+E | 11.9    |  14.4    |p
V0868 Cyg  |192904.43 +285425.9 |UGZ   | 14.3    |< 17.8    |p
V1285 Cyg *|194449.53 +355934.9 |UGZ:  | 13.1    |  14.8    |p
V1363 Cyg  |200611.55 +334237.9 |UGZ   | 13.0    |< 17.6    |p
V1404 Cyg  |215716.37 +521200.5 |UGZ   | 15.7    |< 17.7    |p
V1504 Cyg  |192856.45 +430536.4 |UGZ:  | 13.5    |  17.4    |p
V1505 Cyg  |192948.97 +283254.1 |UGZ   | 15.2    |< 17.5    |p
IS    Del  |203109.63 +162309.8 |UGZ:  | 15.     |< 17.5    |p
AB    Dra  |194906.38 +774423.0 |UGZ   | 11.0    |  15.3    |V
AQ    Eri  |050613.06 -040807.9 |UGZ:  | 12.5    |  16.5    |p
FM    Gru  |220218.88 -430519.0 |UGZ:  | 13.4    |  16.6    |V
AH    Her *|164410.01 +251502.0 |UGZ   | 10.9    |  14.7    |p
TT    Ind  |203337.10 -563344.8 |UGZ   | 14.0    |< 16.5    |p
MN    Lac  |222304.62 +524058.4 |UGZ   | 15.1    |< 18.0    |p
MV    Leo *|102800.07 +214813.6 |UGZ+E | 15.5    |  17.7    |V
V0391 Lyr  |182111.97 +384743.7 |UGZ   | 14.0    |  17.0    |p
V0419 Lyr  |191014.04 +290614.5 |UGZ   | 14.4    |< 17.5    |p
CG    Mus  |122013.12 -741315.0 |UGZ   | 15.9    |  17.0    |p
HP    Nor  |162049.57 -545322.8 |UGZ   | 12.8    |  16.41   |V
AY    Oct  |232750.94 -754040.0 |UGZ:  | 15.0    |  16.1    |p
BI    Ori  |052351.76 +010030.1 |UGZ   | 13.2    |  16.7    |p
CN    Ori *|055207.79 -052500.6 |UGZ   | 11.0    |  16.2    |V
V0344 Ori  |061518.96 +153100.0 |UGZ   | 14.2    |  17.5  : |p
TZ    Per *|021350.94 +582252.7 |UGZ   | 12.0    |  15.6    |V
KT    Per *|013708.51 +505720.5 |UGZ+ZZ| 11.5    |  15.39   |V
PY    Per  |025000.10 +373923.4 |UGZ   | 13.8    |  16.5    |p
V0368 Per  |024732.61 +345828.1 |UGZ:  | 15.2    |< 17.5    |p
V0392 Per *|044321.37 +472127.1 |UGZ:  | 15.     |  17.5    |p
BX    Pup *|075415.56 -241936.3 |UGZ   | 13.76   |  16.0    |V
TW    Tri  |013637.01 +320040.0 |UGZ   | 13.3    |  17.0    |p
VW    Vul *|205745.07 +253025.7 |UGZ   | 13.1    |  16.27   |B
FY    Vul *|194139.96 +214558.7 |UGZ   | 13.4    |  15.33   |B
```

**Comment by Xamidimura** [comment]
Z Cam and AT Cnc *may* be linked to nova eruptions in -76 (i.e. 77 BC/BCE) and 1645, respectively. Of course Z Cam-type dwarf novae (UGZ) in general should not be added to the nova list.

**Comment by Xamidimura** [comment]
Papers: 2012ApJ...756..107S (Z Camelopardalis) and 2017MNRAS.465..739S (AT Cancri)

**Comment by Bill-Gray** [comment]
Ah,  interesting... thanks for that.  Both cases do look somewhat tenuous;  I see why you wrote "_may_ be linked..."  But we have other tenuous cases in the file,  of class N? and N??.

I've put together [a `galnovae.txt` with Z Cam and AT Cnc added](https://www.projectpluto.com/temp/galnovae.txt),  and much of the data from GCVS.  Still a work in progress,  but the basic idea is that they would be at the end of the file with the oldest novae.  I've listed them both as class N??/UGZ.

I notice that the Z Cam paper says they couldn't actually detect expansion from images taken in 2007 and 2010,  but that "detection and measurement of this rate of expansion should be possible in just a few years".  I wonder how much that shell has expanded in 2022.

**Comment by Bill-Gray** [comment]
Since we've got those two objects added,  I'll close this as 'resolved'.
