### ISSUE TITLE
Wrong MAX.MAG value for V2860 Ori

### ISSUE THREAD

**Issue by aaguasca** [Bill-Gray/galnovae#4]
It seems the value of MAX.MAG for V2860 Ori is wrong:
https://github.com/Bill-Gray/galnovae/blob/e508e6ed0a9602d520add278b2c61dcec7cbc530/galnovae.txt#L42

It seems V2860 Ori was caught after the peak and already in the decay phase [1,2], and published data starts after 1 day since the outburst [3] or several days [4].

I suppose the value 0.4 in the MAX.MAG is a typo and the discovery magnitude 9.4 was intended.

references:
[1]. https://www.astronomerstelegram.org/?read=13027
[2]. https://www.aavso.org/aavso-alert-notice-676
[4]. https://iopscience.iop.org/article/10.3847/1538-4357/abeb75/pdf
[3]. https://iopscience.iop.org/article/10.3847/1538-4357/ac8d5e/pdf

**Comment by Bill-Gray** [comment]
Thanks for the fix!

It was either a typo,  or wishful thinking.  We've not had a nova that bright since N Pup 1942... it _would_ be nice!
